apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: default
  labels:
    app: {{ .Release.Name }}
data:
  config.yml: |
    version: 2
    server:
      host: 0.0.0.0
      port: 2345
      embeddedUI:
        enabled: false
      ssl:
        enabled: false
    engine:
      db:
        host: dblabwebtest.exist.ua
        port: 30032
        user: postgres
        password: strs5348
        dbname: postgres
