apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: default
  labels:
    app: {{ .Release.Name }}
data:
  config.yml: |
    version: 2
    server:
      host: {{ .Values.config.server.host }}
      port: {{ .Values.config.server.port }}
      embeddedUI:
        enabled: {{ .Values.config.server.embeddedUI.enabled }}
        dockerImage: "{{ .Values.config.server.embeddedUI.dockerImage }}"
        host: {{ .Values.config.server.embeddedUI.host }}
        port: {{ .Values.config.server.embeddedUI.port }}
      ssl:
        enabled: {{ .Values.config.server.ssl.enabled }}
    engine:
      db:
        host: {{ .Values.config.engine.db.host }}
        port: {{ .Values.config.engine.db.port }}
        user: {{ .Values.config.engine.db.user }}
        password: {{ .Values.config.engine.db.password }}
        dbname: {{ .Values.config.engine.db.dbname }}
