apiVersion: v1
kind: ConfigMap
metadata:
  name: test1-config
  namespace: default
data:
  config.yml: |
    version: 2
    server:
      host: 0.0.0.0
      port: 2345
      ui:
        enabled: true
        host: 0.0.0.0
        port: 8080
      ssl:
        enabled: false
    engine:
      db:
        host: dblabwebtest.exist.ua
        port: 30032
        user: postgres
        password: strs5348
        dbname: postgres
