apiVersion: apps/v1                      # API-версия для Deployment
kind: Deployment                         # Объект - Deployment
metadata:
  name: "{{ .Release.Name }}-deployment" # Название (зависит от имени релиза)
spec:
  replicas: {{ .Values.replicas }}       # Количество подов (реплик)
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-dind"    # Метка, по которой Deployment выбирает поды
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-dind"  # Должна совпадать с selector
    spec:
      containers:
        # --- (1) Контейнер с Docker-in-Docker ---
        - name: dind
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          securityContext:
            privileged: true            # Для DinD нужен привилегированный режим
          command: [ "dockerd" ]        # Запуск Docker Daemon
          args:
            - "--host=tcp://0.0.0.0:2375"           # (Необязательный) TCP-порт
          ports:
            - containerPort: 2375       # Порт, на котором слушает Docker Daemon (TCP)
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock  # Общий сокет для Docker

        # --- (2) Контейнер с dbLab ---
        - name: dblab
          image: "{{ .Values.dblab.image }}:{{ .Values.dblab.tag }}"
          env:
            # Рекомендуется передавать строку подключения через PG_CONNECTION_STRING:
            - name: PG_CONNECTION_STRING
              value: "postgresql://{{ .Values.dblab.user }}:{{ .Values.dblab.password }}@{{ .Values.dblab.host }}:{{ .Values.dblab.port }}/{{ .Values.dblab.dbname }}"
            
            # Пароль для админского Web-UI
            - name: ADMIN_PASSWORD
              value: "{{ .Values.dblab.dbAdminPassword }}"

            # Отключить HTTPS, если нет сертификата (по документации dbLab)
            - name: DBLAB_NO_SSL
              value: "1"

            # dbLab по умолчанию слушает 127.0.0.1, если нужно, выставим на 0.0.0.0:
            - name: DBLAB_LISTEN_HOST
              value: "0.0.0.0"

            # Порт, на котором доступно Web-UI и API dbLab
            - name: DBLAB_LISTEN_PORT
              value: "2345"
            # Указываем, что dbLab должен использовать TCP
            - name: DOCKER_HOST
              value: "tcp://127.0.0.1:2375"
