apiVersion: apps/v1                 # Используем API-версию для Deployment
kind: Deployment                    # Говорим, что это Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"  # Название деплоймента берём из имени релиза
spec:
  replicas: {{ .Values.replicas }}        # Количество подов, читаем из values.yaml
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-dind"     # По этой метке определяем, какие поды управляет
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-dind"   # Метка, которая должна совпадать с selector выше
    spec:
      containers:
        - name: dind                           # Имя контейнера
          image: "{{ .Values.image }}:{{ .Values.tag }}" # Образ берём из values.yaml
          securityContext:
            privileged: true                  # Необходимо для DinD
          command: [ "dockerd" ]             # Запуск Docker Daemon
          args:
            - "--host=unix:///var/run/docker.sock" # Локальный Unix-сокет
            - "--host=tcp://0.0.0.0:2375"          # TCP-сокет, если нужен внешний доступ
          ports:
            - containerPort: 2375             # Порт, на котором слушает Docker Daemon
