apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: install-docker
          image: ubuntu:22.04
          command:
            - /bin/bash
            - -c
            - |
              set -e
              # Проверяем, если dockerd использует сокет, и убиваем процесс
              if [ -e /var/run/docker.sock ]; then
                echo "Docker socket exists, trying to kill processes using it"
                fuser -k /var/run/docker.sock || true  # Завершаем процесс, использующий сокет
                rm -rf /var/run/docker.sock  # Удаляем сокет
              fi
              apt-get update
              apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
              add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              apt-get update
              apt-get install -y docker-ce
              dockerd --host=unix:///var/run/docker.sock &
              sleep 5
              while ! docker ps >/dev/null 2>&1; do sleep 2; done
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: false  # Разрешаем запись на сокет, чтобы Docker работал

      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /home/dblab/bin/dblab-server
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock  # Монтируем сокет Docker
            - name: config-volume
              mountPath: /home/dblab/configs/server.yml
              subPath: config.yml
          ports:
            - containerPort: {{ .Values.config.server.port }}
              name: api
            - containerPort: {{ .Values.config.server.embeddedUI.port }}
              name: ui

      volumes:
        - name: docker-socket
          emptyDir: {}  # Используем emptyDir для создания сокета внутри контейнера
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
