apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-dblab-pv  # Уникальное имя PV
  labels:
    app: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}  # Размер хранилища из values.yaml
  accessModes:
    - "{{ .Values.persistence.accessModes }}"
  persistentVolumeReclaimPolicy: Retain  # PV сохраняется после удаления PVC
  hostPath:
    path: {{ .Values.persistence.path }}  # Путь на хосте из values.yaml
