apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  accessModes:
    {{- range .Values.persistence.accessModes }}
      - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
