image:
  repository: postgresai/dblab-server
  tag: 3.3-latest
  pullPolicy: IfNotPresent

config:
  version: 2
  server:
    host: 0.0.0.0
    port: 2345
    ui:
      enabled: true
      host: 0.0.0.0
      port: 8080
    ssl:
      enabled: false
  engine:
    db:
      host: dblabwebtest.exist.ua
      port: 30032
      user: postgres
      password: strs5348
      dbname: postgres

ports:
  api: 2345
  ui: 8080
  postgres: "6000-6100"
