# Параметры образа контейнера
image:
  repository: "nginx"  # Репозиторий образа Nginx
  tag: "latest"  # Тег образа, используется latest, но можно изменить на конкретную версию
  pullPolicy: "IfNotPresent"  # Политика загрузки образа (не загружать, если уже есть)

# Количество реплик для деплоймента
replicaCount: 1  # Количество подов, создаваемых деплойментом

# Порт для Nginx
nginxPort: 14080  # Порт, на котором Nginx будет сервировать изображение

# Путь к папке и URL для скачивания изображения
folderPath: "/folder1/images"  # Путь к папке, которую создаст busybox
imageURL: "https://www.interfax.ru/ftproot/photos/photostory/2014/04/04/600dart4.jpg"  # URL изображения для скачивания

# Настройки проверки здоровья (liveness и readiness probes)
livenessProbe:
  httpGet:
    path: /
    port: 14080  # Порт, на котором будет проверяться живучесть контейнера
  initialDelaySeconds: 30  # Время задержки перед началом проверки
  periodSeconds: 10  # Интервал между проверками

readinessProbe:
  httpGet:
    path: /
    port: 14080  # Порт, на котором будет проверяться готовность контейнера
  initialDelaySeconds: 15  # Время задержки перед началом проверки
  periodSeconds: 5  # Интервал между проверками