# API-версия для Service
apiVersion: v1
kind: Service  # Указывает, что мы создаем сервис
metadata:
  name: "{{ .Release.Name }}-postgres"  # Уникальное имя сервиса
  labels:
    app: "{{ .Chart.Name }}"  # Метка для связи с другими объектами
spec:
  type: {{ .Values.service.type }}  # Тип сервиса: ClusterIP, NodePort, LoadBalancer
  ports:
  - port: {{ .Values.service.port }}  # Порт, по которому будет доступен сервис
    targetPort: 5432  # Порт внутри контейнера PostgreSQL
    nodePort: {{ .Values.service.nodePort | default 30001 }}  # Внешний порт (по умолчанию 30001)
    protocol: TCP  # Используемый протокол
  selector:
    app: "{{ .Chart.Name }}"  # Подключение к подам, которые имеют эту метку
