apiVersion: v1  # Указывает, что это ресурс Kubernetes версии v1
kind: Pod  # Тип ресурса — Pod
metadata:
  name: {{ .Release.Name }}-folder-pod  # Имя Pod, уникальное для каждого релиза
spec:
  containers:  # Список контейнеров внутри Pod
    - name: folder-container  # Имя контейнера
      image: busybox  # Образ контейнера (busybox — минимальный Linux)
      command:
        - sh
        - "-c"
        - >
           mkdir -p /data/{{ .Values.folderName }}/$(dirname "{{ .Values.imagePath }}") &&  # Создаём путь до файла
           echo "Sample Image" > /data/{{ .Values.folderName }}/{{ .Values.imagePath }} &&  # Создаём файл
           sleep 3600;  # Поддерживаем контейнер активным
      volumeMounts:  # Монтируем том, чтобы данные сохранялись на сервере
        - name: data-volume
          mountPath: /data  # Путь в контейнере
  volumes:  # Указываем том
    - name: data-volume
      hostPath:
        path: /data  # Путь на сервере, где хранятся данные
        type: Directory  # Тип тома — папка