apiVersion: v1
kind: Pod
metadata:
  name: folder-creator
spec:
  containers:
    - name: folder-container
      image: busybox
      command:
        - sh
        - -c
        - |
          mkdir -p /mnt/data{{ .Values.folderPath }} && \
          wget -O /mnt/data{{ .Values.folderPath }}/image.jpg {{ .Values.imageURL }} && \
          sleep 3600
      volumeMounts:
        - name: data-volume
          mountPath: /mnt/data  # Путь внутри контейнера, где будут храниться данные
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: {{ .Values.nginxPort }}
      volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html          
  volumes:
    - name: data-volume
      hostPath:
        path: /mnt/data  # Путь на сервере, где будут храниться данные
        type: Directory  # Указываем, что это директория на хосте
