apiVersion: v1
kind: Pod
metadata:
  name: folder-creator
spec:
  containers:
    - name: folder-container
      image: busybox
      command:
        - sh
        - -c
        - |
          mkdir -p /mnt/data/{{ .Values.folderName }} && \
          echo "Sample Image" > /mnt/data/{{ .Values.folderName }}/{{ .Values.imagePath }} && \
          sleep 3600
      volumeMounts:
        - name: data-volume
          mountPath: /mnt/data  # Путь в контейнере
  volumes:
    - name: data-volume
      hostPath:
        path: /mnt/data  # Путь на сервере, где хранятся данные
        type: Directory  # Тип тома — папка
