apiVersion: v1
kind: Pod
metadata:
  name: folder-creator
spec:
  containers:
    - name: folder-container
      image: busybox
      command:
        - sh
        - -c
        - |
          mkdir -p /mnt/data{{ .Values.folderPath }} && \
          echo "Sample Image" > /mnt/data{{ .Values.folderPath }}/{{ .Values.imageName }} && \
          sleep 3600
      volumeMounts:
        - name: data-volume
          mountPath: /mnt/data  # Путь внутри контейнера, где будут храниться данные
  volumes:
    - name: data-volume
      hostPath:
        path: /mnt/data  # Путь на сервере, где будут храниться данные
        type: Directory  # Указываем, что это директория на хосте
