apiVersion: v1
kind: Pod
metadata:
  name: folder-creator
spec:
  containers:
    - name: folder-container
      image: busybox
      command:
        - sh
        - "-c"
        - >
          mkdir -p /data/{{ .Values.folderName }} &&  # Создаём папку
          echo "Sample Image" > /data/{{ .Values.folderName }}/{{ .Values.imagePath }} &&  # Создаём файл
          sleep 3600;  # Поддерживаем контейнер активным
      volumeMounts:
        - name: data-volume
          mountPath: /data  # Путь внутри контейнера, где будут храниться данные
  volumes:
    - name: data-volume
      hostPath:
        path: /mnt/data  # Путь на сервере, где будут храниться данные
        type: Directory  # Указываем, что это директория на хосте
