apiVersion: v2                         # Версия API для Helm 3
name: dind-in-DinD                       # Имя чарта
description: Helm chart for DinD + dbLab (v1.14.1)
version: 0.1.2                         # Версия самого чарта
