apiVersion: networking.k8s.io/v1  # Версия API для Ingress.
kind: Ingress  # Тип ресурса — Ingress.
metadata:
  name: nginx-ingress-test  # Имя Ingress.
spec:
  rules:
    - host: {{ .Values.ingress.host }}  # Хост для Ingress. Пустой для всех запросов.
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-ingress-test  # Имя Service.
                port:
                  number: {{ .Values.service.port }}  # Порт Service из values.yaml.
