apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-test  # Имя Service.
spec:
  type: NodePort  # Тип Service, чтобы обрабатывать внешние запросы.
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nginx.ports.http }}  # HTTP-порт, который слушает Service.
      targetPort: {{ .Values.nginx.ports.http }}  # Порт внутри контейнера NGINX для HTTP.
      nodePort: {{ .Values.nginx.ports.http }}  # Внешний порт для HTTP.
    - name: https
      protocol: TCP
      port: {{ .Values.nginx.ports.https }}  # HTTPS-порт, который слушает Service.
      targetPort: {{ .Values.nginx.ports.https }}  # Порт внутри контейнера NGINX для HTTPS.
      nodePort: {{ .Values.nginx.ports.https }}  # Внешний порт для HTTPS.
  selector:
    app: nginx-ingress-test  # Соединяем с подами.
